---
title: "R Notebook"
output: html_notebook
---

```{r libraries, include = FALSE}
library(tidyverse)
library(scales)
library(hrbrthemes)
library(readxl)
```

### Data used

Download electoral data from 2015 election and from EU referendum
```{r data}
if (!file.exists("electionResults2015.xlsx")) {
  download.file("http://www.electoralcommission.org.uk/__data/assets/excel_doc/0011/189623/2015-UK-general-election-data-results-WEB.xlsx", "electionResults2015.xlsx")
}
if (!file.exists("referendumResults2016.csv")) {
  download.file("http://www.electoralcommission.org.uk/__data/assets/file/0014/212135/EU-referendum-result-data.csv",  "referendumResults2016.csv")
}

```

### Select and tidy data

```{r selectData}
candidates <- 
  read_excel("electionResults2015.xlsx", sheet = 2)
constituency <- 
  read_excel("electionResults2015.xlsx", sheet = 3)
results <- 
  read_excel("electionResults2015.xlsx", sheet = 4)
partyNames <- 
  read_excel("electionResults2015.xlsx", sheet = 5)

votingData <- 
  left_join(
    candidates %>%
      dplyr::select(PANO, Surname, `Constituency ID `, `Party abbreviation`, Votes),
    constituency %>%
      select(PANO, `Constituency ID`, `Constituency Name`, Electorate, 
        `Valid Votes`, Region),
    by = c("PANO", "Constituency ID " = "Constituency ID")
  ) %>% 
  group_by(PANO) %>%
  mutate(
    resultRank = row_number(desc(Votes)),
    winningVotes = max(Votes),
    shortfallVotes = winningVotes - Votes,
    shortfallVotesPpnElectorate = shortfallVotes / Electorate,
    shortfallVotesPpnVoted = shortfallVotes / `Valid Votes`
  )
```

```{r}
scottishData <- 
  votingData %>%
  filter(Region == "Scotland")

topMarginals <- 
  scottishData %>%
  ungroup() %>%
  filter(resultRank == 2) %>%
  mutate(shortfallPpnVotedRank = min_rank(shortfallVotesPpnVoted)) %>%
  filter(shortfallPpnVotedRank <= 10) %>%
  select(PANO, shortfallPpnVotedRank) %>%
  left_join(
    scottishData %>%
      filter(resultRank <= 3),
    by = c("PANO")
  ) %>%
  dplyr::arrange(shortfallPpnVotedRank, resultRank)

```

```{r}

topMarginals %>%
  filter(resultRank > 1) %>%
  group_by(PANO) %>%
  mutate(xAxis = 
      as.character(percent(shortfallVotesPpnVoted))) %>%
  ggplot() +
  theme_ipsum() +
  geom_col(
    aes(x = resultRank, y = shortfallVotesPpnVoted, 
      fill = `Party abbreviation`), alpha = 0.5) +
  geom_text(
    aes(x = resultRank, y = 0, label = shortfallVotes), hjust = 0) +
  scale_fill_ipsum() +
  scale_y_continuous(labels = percent) +
  scale_x_discrete(labels = NULL) +
  ylab("Shortfall (as pct of votes cast)") +
  xlab(NULL) +
  coord_flip() +
  facet_wrap(~PANO, ncol = 5, scales = "free_x") +
  theme(legend.position = "bottom", legend.direction = "horizontal")

```


Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).
